Make this plugin npm compatible with eslint 4
FontoXML/eslint-config-fontoxml pull request #5
Opened 2017-06-27 10:02 UTC by ThomasBrekelmans

Add the eslint and eslint-plugin-react version ranges that we use in fontoxml-vendor-fds which uses eslint 4.
This prevents annoying NPM warnings.

Eslint 4 introduces new rules that we could take advantage of, but it's not immediately necessary to do so.

2017-06-27 10:06 UTC, DrRataplan commented
Let's just change the dep on eslint to `^4.0.0`. A range with multiple versions will cause issues, they have released a major version for a reason.

Let's at least make it `^3.0.0 || ^4.0.0`, I see no reason to block `4.1.0`.

2017-06-28 18:02 UTC, bwrrp commented
3.9.0 was the current version of eslint at the time these rules were specified. I'm not sure how far back we can go with the current set along the 3.x branch. The changes from 3.x to 4.x seem pretty small, and I don't thing the extra rules in eslint:recommended will cause any trouble, so declaring compatibility with both looks fine.

However, I guess if 4.1.x works, 4.0.x should work as well? If so, please change the range to `^3.9.0 || ^4.0.0` (and similar for eslint-plugin-react) to maximize compatibility.

2017-06-28 18:02 UTC, bwrrp requested changes
3.9.0 was the current version of eslint at the time these rules were specified. I'm not sure how far back we can go with the current set along the 3.x branch. The changes from 3.x to 4.x seem pretty small, and I don't thing the extra rules in eslint:recommended will cause any trouble, so declaring compatibility with both looks fine.

However, I guess if 4.1.x works, 4.0.x should work as well? If so, please change the range to `^3.9.0 || ^4.0.0` (and similar for eslint-plugin-react) to maximize compatibility.

2017-11-06 12:20 UTC, merged

2017-11-06 12:21 UTC, ThomasBrekelmans commented
Implemented suggestions for wider version range and rebased + pushed to master.